config/routes.rb
Rails.application.routes.draw do
  
  devise_for :appusers
  resources :users
  resources :articles do
    resources :comments, only: [:create, :update, :destroy, :show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'hora', to: 'welcome#index'
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appuser.rb
class Appuser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
  has_many :comments 
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :appuser
    has_many :comments
    validates :title, presence: true, uniqueness: true
    validates :body, presence: true, length: { minimum: 12 }
    before_create :set_visits_count
    
    def update_visits_count
        self.update(visits_count: self.visits_count + 1)
    end

    private

    def set_visits_count
        self.visits_count=0
        end

    
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :appuser
  belongs_to :article
  validates :body, presence: true

end

app/models/devise_helper.rb
module DeviseHelper
    def devise_error_messages!
      return "" unless devise_error_messages?
  
      messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
      sentence = I18n.t("errors.messages.not_saved",
                        :count => resource.errors.count,
                        :resource => resource.class.model_name.human.downcase)
  
      html = <<-HTML
      <div id="error_explanation">
      <h2>blablavblablablab</h2>
        <h2>#{sentence}</h2>
        <ul>#{messages}</ul>
      </div>
      
      HTML
  
      html.html_safe
    end
  
    def devise_error_messages?
      !resource.errors.empty?
    end
  
  end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    #before_action :validate_user, except: [:show, :index]
    before_action :authenticate_appuser!, except: [:show,:index]
    before_action :set_article,except:[:index,:new,:create]
    #before_action :authenticate_appuser!
    #GET /article
    def index
    @articles = Article.all
    end     

    #GET / article/:id
    def show  
        @article.update_visits_count
        @comment = Comment.new

    end

    def new
        @article = Article.new
    end

    #POST /article
    def create 
        @article = current_appuser.articles.new(article_params) 
        #@article = Article.new(title: params[:article][:title],body: params[:article][:body]) 
        

        if @article.save
        redirect_to @article
        else
            render template: "articles/new"
            #render :new            
        end
    end

    def edit
    end

    #put /article/:id
    def update
        if @article.update(article_params)
            redirect_to @article
        else
            render :edit
        end
    end 

    def destroy
         @article.destroy
         redirect_to articles_path
    end


    private

    def article_params
        params.require(:article).permit(:title,:body)
    end

    def validate_user
        redirect_to new_appuser_session_path, notice: "Es necesario iniciar sesion"
    end

    def set_article
        @article = Article.find(params[:id])
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :update, :destroy]
  before_action :set_article
  before_action :authenticate_appuser!

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = current_appuser.comments.new(comment_params)
    @comment.article=@article

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.article, notice: 'Comment was successfully created.' }
        format.js { render :show }
        format.json { render :show, status: :created, location: @comment.article }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.article, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @article, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:appuser_id, :article_id, :body)
    end

    def set_article
      @article=Article.find(params[:article_id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_formNew.html.erb
<h1><%= name ||= "Crear"%> articulo</h1>
<%= form_for(@article) do |f| %>




<%= @article.errors.full_messages.each do |message|%>
<div class="redbe whiteFont spacetap">
    * <%= message %>
</div>
<% end %>

   <!--<%= @article.errors.full_messages.each do |message| %>
    <%= javascript_tag "Materialize.toast('#{message}', 4000)" %>

<%end%>-->

    <div class="field">
        <%= f.text_field :title, placeholder: "Titulo",  id: "valida"%>
    </div>
    <div class="field">
    <%= f.text_area :body, placeholder: "Escribe aqui el articulo", style: "height:200px;" %>
    
    </div>
    <!-- <button class="btn waves-effect waves-light floating" type="submit" name="action">Guardar
    <i class="material-icons right">send</i>
  </button>-->
      <%= f.submit "Guardare", class:"btn waves-effect waves-light" %>
<% end %>

app/views/articles/edit.html.erb
<%= render "formNew", name: "Editar"%>

app/views/articles/index.html.erb
<!--<%= @articles.inspect %>-->

<% if !appuser_signed_in?%>
<span style="color: red">Inicia sesion para eliminar o editar</span>
<% end %>

<div class="row">
<% @articles.each do |article|%>
<%if appuser_signed_in?%>
<div class="col s12 m12 l6 ">
    <h6 class="header"><%= link_to article.title,article %>
   </h6>
    <div class="card horizontal">
      <div class="card-image">
        <!--<img src="../../../images/quad.jpg">-->
        <%= image_tag("quad.jpg", :alt => "rss feed") %>
      </div>
      <div class="card-stacked">
        <div class="card-content">
          <p><%= article.body %> </p>
        </div>
        <div class="card-action">
        <%= link_to "eliminar",article, method: :delete %>        </div>
      </div>
    </div>
  </div>
<% else %>

<div class="col s12 m7">
    <h2 class="header"><%= article.title %>
   </h2>
    <div class="card horizontal">
      <!--<div class="card-image">
        <img src="https://lorempixel.com/100/190/nature/6">
      </div>
      -->
      <div class="card-stacked">
        <div class="card-content">
          <p><%= article.body %> </p>
        </div>
        <div class="card-action">
        <p>Para realizar acciones inicia sesión</p>
      </div>
    </div>
  </div>
<% end %> 


<% end %>

</div>

app/views/articles/new.html.erb
<%= render 'formNew', user: @user %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<div>
<%= @article.body %>

</div>

<%unless @article.appuser_id.nil?%>
<p>
Escrito por: <%=@article.appuser.email%>
</p>
<% end %>

<%unless @article.visits_count.nil?%>
<p>
Visitas: <%=@article.visits_count%>
</p>
<% end %>

<div>
<h3>Comentarios</h3>
<%= render "comments/form" %>
<ul id="comments-box">
<% @article.comments.each do |comment|%>
<li><%= comment.body%> - <%= comment.appuser.email%></li>
<% end %>
</ul>
</div>


<%= link_to 'Volver', articles_path %>
<%= link_to 'Editar', edit_article_path(@article) %>

app/views/comments/_form.html.erb
<%= form_with(model: [@article,@comment], remote: true, html:{id:"comments_form"}) do |form| %>



  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Appuser:</strong>
  <%= @comment.appuser %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PbaPostgres</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <%= render "partials/navigation"%>    
          
  </header>
  <main>
  <!--<p class="notice"><%= notice %></p>
  <p class="error"><%= alert %></p>-->

  
  <% unless flash.empty? %>
      <script>
        <% flash.each do |f| %>
        <% type=f[0].to_s.gsub('alert', 'red').gsub('warning', 'orange').gsub('success', 'green') %>
        Materialize.toast('<%= f[1] %>', 4000, '<%= type %>')
        <% end %>
      </script>
      <% end %>
 
   
        <div class="container">

    <%= yield %>
    </div>
    </main>
    <footer  class="page-footer">
<div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Footer Content</h5>
                <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2014 Copyright Text
            <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
            </div>
          </div>
  </footer>
  </body>
</html>

app/views/partials/_navigation.html.erb
<nav>
    <div class="nav-wrapper">
      <a href="#!" class="brand-logo">Logo</a>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
              <li><a class="waves-effect waves-light btn">Button</a></li>

        <li><a href="sass.html">Sass</a></li>
        <li><a href="badges.html">Components</a></li>
        <li><a href="collapsible.html">Javascript</a></li>
        <li><a href="mobile.html">Mobile</a></li>
        <%if appuser_signed_in? %>
        <li>
        <%= link_to "Cerrar sesion", destroy_appuser_session_path, method: :delete%>
        </li>
        <%else%>
        <li>
        <%= link_to "Iniciar sesion", new_appuser_session_path%>
        </li>
        <li>
        <%= link_to "Crear cuenta", new_appuser_registration_path%>
        </li>
        <% end %>

      </ul>
      <ul class="side-nav" id="mobile-demo">
        <li><a href="sass.html">Sass</a></li>
        <li><a href="badges.html">Components</a></li>
        <li><a href="collapsible.html">Javascript</a></li>
        <li><a href="mobile.html">Mobile</a></li>
      </ul>
    </div>
  </nav>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= render 'form', artlcle: @article %>

<%= link_to 'Back', articles_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h2>This is a test heroku</h2>
<p>
  The time is now: <%= Time.now %>
</p>

<h2>This is a test heroku</h2>